---
# playbooks/create-default-infrastructure.yml
# 
# Create a default AWS VPS if one does not exist.
#
# See plays/create-specific-infrastructure.yml for comparison.

- name: create a virtual private cloud
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: gather facts from the ec2 virtual private cloud
      ec2_vpc_net_facts:
        region: "{{ ec2_region }}"
      register: ec2_vpc_net_facts

    - name: create a default vpc if one does not exist
      command: aws ec2 create-default-vpc
      when: ec2_vpc_net_facts.vpcs | selectattr("is_default", "equalto", true) | list | length == 0

    # - debug: msg={{ ec2_vpc_net_facts.vpcs | selectattr("is_default", "equalto", true) | list | length == 0 }}

# vim:sw=2:ts=2:et
