# plays/destroy-ec2-instances.yml
#
# Destroy the EC2 instance

- name: destroy ec2 instances
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: destroy ec2 instances
      amazon.aws.ec2_instance:
        # instance_ids: "{{ hostvars[inventory_hostname].instance_id }}"
        # region: "{{ ec2_region }}"
        state: absent
        filters:
          tag:name: demo

# vim:sw=2:ts=2:et


